# Ansible Playbook for Subutai Gollum blueprint
---

- hosts: all
  gather_facts: false
  remote_user: root
  tasks:
  
    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    - name: Install tools
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        dpkg_options: force-confdef,force-confold,force-unsafe-io
      with_items: 
        - wget
        - xz-utils
        - make
        - zlib1g-dev
        - libicu-dev
        - build-essential
        - git
        - nginx
        - ca-certificates
        - cmake
        - libssl-dev
        - pkg-config

    - name: Extract Ruby 2.7.1 into /tmp
      unarchive:
        src: https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.xz
        dest: /tmp/
        remote_src: yes
        
    - name: Configure Ruby 2.7.1
      shell: ./configure chdir=/tmp/ruby-2.7.1
      tags: packages, ruby
        
    - name: Make
      shell: make chdir=/tmp/ruby-2.7.1
      tags: packages, ruby
        
    - name: Install Ruby 2.7.1
      shell: make install chdir=/tmp/ruby-2.7.1
      become: yes
      become_user: root
      tags: packages, ruby
      
    - name: Remove tmp files used for Ruby 2.7.1 installation
      file: path={{ item }} state=absent
      with_items:
        - /tmp/ruby-2.7.1.tar.xz
        - /tmp/ruby-2.7.1
      tags: packages, ruby   
      
    - name: Install Gollum
      gem:
        name: "{{ item }}"
        state: present
        user_install: no
      with_items:
        - gollum
    
    - name: Create user
      user:
        name: gollum
        shell: /bin/bash
        create_home: yes
        system: no

    - name: Copy git configuration
      copy:
        src: etc/gitconfig
        dest: /home/gollum/.gitconfig
        owner: gollum
        group: gollum
        mode: 0644

    - name: Clean up
      file:
        path: /home/gollum/wiki
        state: absent

    - name: Create wiki directory
      file:
        path: /home/gollum/wiki
        state: directory

    - name: Initialize wiki repository
      raw: cd /home/gollum/wiki && git init . && cd -

    - name: Set file permissions
      file:
        dest: "{{ item }}"
        owner: gollum
        group: gollum
        recurse: yes
      with_items:
        - /home/gollum/wiki

    - name: Create App directory
      file:
        path: /usr/local/etc/gollum
        state: directory
    
    - name: Copy App configuration
      copy:
        src: etc/config.rb
        dest: /usr/local/etc/gollum/config.rb
        owner: root
        group: root
        mode: 0644

    - name: Install gollum.service
      copy:
        src: systemd/gollum.service
        dest: /lib/systemd/system/gollum.service
        owner: root
        group: root
        mode: 0644

    - name: Start gollum.service
      systemd:
        name: gollum.service
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Install nginx configuration
      copy:
        src: etc/gollum.conf
        dest: /etc/nginx/sites-available/gollum.conf
        owner: root
        group: root
        mode: 0644

    - name: Activate nginx configuration
      file:
        src: /etc/nginx/sites-available/gollum.conf
        dest: /etc/nginx/sites-enabled/gollum.conf
        state: link

    - name: Remove default configuration
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Restart nginx
      service:
        name: nginx
        enabled: yes
        state: restarted

# vim: ts=2 et nowrap autoindent
